#!/bin/bash

adress=`ip r | grep default | cut -d ' ' -f 3`
up=`ping -q -w 1 -c 1 $adress > /dev/null && echo ok || echo error`

if [ $up == ok ]; then
	echo "Updatind dbases.xm"
 	echo "Checking versions, if is the same, continue, else update to new one"
    echo "Using the existing files in srst2/data/mlst" 
else

fi

