#!/bin/bash
## La cantidad de memoria requerida no puede ser mayor a 22GB (cola CI).
## La cantidad de memoria requerida no puede ser mayor a 62GB (cola CA).
## El mayor numero de nodes puede llegar a ser máximo 21 (cola CI) (21*12)=252 
## El mayor numero de nodes puede llegar a ser máximo 8 (cola CI)  (8*32)=256

### Nombre de la tarea
#PBS -N sample_1

###Opciones de ejecucion (nodes=numero de nodos; ppn=procesadores por nodo)
#PBS -l nodes=1:ppn=32

###Tiempo ejecucion maximo (no es indispensable, pero es recomendable para encolar el trabajo correctamente)
##PBS -l walltime=48:00:00

### Nombre de la cola
#PBS -q CA

### Entra al directorio de trabajo actual
##echo Working directory is $PBS_O_WORKDIR


####PBS_NP=24
####PBS_NUM_PPN=12

export OMP_NUM_THREADS=$PBS_NP; 
cd $PBS_O_WORKDIR

source /opt/intel/icsxe/2012.0.032/ictvars-nmpi.sh

### Obtiene el numero de procesadores en que
##se ejecutara la tarea (nodos X ppn) y lo
##guarda en la variable de entorno $NP
NP=`(wc -l < $PBS_NODEFILE) | awk '{print $1}'`

cat $PBS_NODEFILE |sort|uniq> mpd.hosts
NM=$(cat mpd.hosts|wc -l |awk '{print $1}')

mkdir $PBS_O_WORKDIR/admon;
echo $NM > $PBS_O_WORKDIR/admon/nm-$PBS_JOBNAME.txt;
echo $NP > $PBS_O_WORKDIR/admon/np-$PBS_JOBNAME.txt;
env      > $PBS_O_WORKDIR/admon/entorno-$PBS_JOBNAME.txt;

export OMP_NUM_THREADS=2; 

/usr/local/velvet/intel/1.2.03/velvet_1.2.03-intel/velveth /scratch/users/jgmena/$PBS_JOBNAME-$PBS_JOBID  90  $PBS_JOBNAME.fasta

cp -rf /scratch/users/jgmena/$PBS_JOBNAME-$PBS_JOBID $PBS_O_WORKDIR/.

rm -rf /scratch/users/jgmena/$PBS_JOBNAME-$PBS_JOBID;

exit 0
### Termina el script de PBS
